// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExceptionSnapshotExtension
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidExceptionPackageString = "adc51aeb-591e-44f7-99e8-6dc173da31a0";
        public static Guid guidExceptionPackage = new Guid(guidExceptionPackageString);

        public const string guidExceptionPackageCmdSetString = "c69520d0-ae2f-4b7b-b0fa-b629bbf817b8";
        public static Guid guidExceptionPackageCmdSet = new Guid(guidExceptionPackageCmdSetString);

        public const string guidImagesString = "9f98e7eb-ee44-47c0-a3cd-9950bb4ee488";
        public static Guid guidImages = new Guid(guidImagesString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int SnapshotWindowCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}
