// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExceptionSnapshotExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "ExceptionSnapshotExtension.4d2a2777-29d1-474f-930b-4810f1d25cae";
        public const string Name = "Exception Snapshot";
        public const string Description = @"Manage ""BreakOnFirstChance"" setting for individual exceptions or group of exceptions with ease.";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Volodymyr Herus";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
